spring.application.name=P1_DSS
spring.datasource.url=jbdc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=root
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.security.user.name=admin
spring.security.user.password=root
spring.security.user.roles=ADMIN

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true

server.address=0.0.0.0
server.port=8080



